name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity Builder
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.37f1
          targetPlatform: StandaloneWindows64

      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.37f1
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
